baseURL: /
languageCode: en-us
build:
  writeStats: true
title: HEy 
# Uncomment below to use aafu as hugo theme. See instructions in README.md
theme: aafu

params:
  author: Darshan Baral # thanks for the theme
  description: HEy 
  copyright: Â© 2025 Hari Chalise
  theme:
    mainTheme: dark
    showAttribute: false
    singlePage: true 
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: experiences
    - item: education
#    - item: publications
    - item: projects
    - item: skills
      panel_id: skill-panel
    - item: hobbies
